
find_package(Git)

if (GIT_FOUND)
	execute_process(
		COMMAND ${GIT_EXECUTABLE} describe --long --dirty
		WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
		OUTPUT_VARIABLE CRIB_VERSION_FULL
		OUTPUT_STRIP_TRAILING_WHITESPACE)

	execute_process(
		COMMAND ${GIT_EXECUTABLE} rev-parse --abbrev-ref HEAD
		WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
		OUTPUT_VARIABLE CRIB_VERSION_BRANCH
		OUTPUT_STRIP_TRAILING_WHITESPACE)
endif()

if ("${CRIB_VERSION_FULL}" MATCHES "^([0-9]+\\.[0-9]+)-([0-9]+)-g([0-9a-f]+)(-dirty)?$")
	set(CRIB_VERSION_TAG   ${CMAKE_MATCH_1})
	set(CRIB_VERSION_PATCH ${CMAKE_MATCH_2})
else()
	set(CRIB_VERSION_TAG "0.0")
	set(CRIB_VERSION_PATCH "0")
endif()
